- hosts: all
  pre_tasks:
    - name: updating packages
      become: true
      package: update_cache=yes

  tasks:
    - name: Install stow and git
      become: true
      package:
        state: present
        name:
          - stow
          - git

    - name: checkout dotfiles repo
      ansible.builtin.git:
        repo: "git@github.com:JesseZomer/dotfiles.git"
        dest: /home/{{ ansible_user_id }}
        version: "HEAD"

    - name: "stow dotfiles"
      shell: stow -d ~/dotfiles *
      changed_when: false
