- hosts: all
  pre_tasks:
    - name: updating packages
      become: true
      package: update_cache=yes

    # - name: Install OpenJDK 11
    #   become: true
    #   apt:
    #     name:
    #       - java-11-openjdk-devel
    #       - java-11-openjdk-jmods
    #       - java-11-openjdk-src
    #   state: present

    - name: Install Maven
      become: true
      package:
        state: present
        name:
          - maven

  roles:
    - gantsign.intellij
    - { role: wildfly, tags: wildfly }

  tasks:
    - name: checkout iridium repo
      ansible.builtin.git:
        repo: "git@github.com:topicusonderwijs/iridium.git"
        dest: /home/{{ ansible_user_id }}/dev/iridium
        key_file: /home/{{ ansible_user_id }}/.ssh/id_ed25519
        accept_hostkey: true
        update: true
        version: master

  
