- hosts: all
  pre_tasks:
    - name: updating packages
      become: true
      package: update_cache=yes

  roles:
    - { role: applications, become: true }
    - { role: brave, become: true }

- name: configure gnome
  import_playbook: gnome.yml

- name: install ssh keys
  import_playbook: ssh.yml
  vars:
    source_key: "files/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    ssh_pass: "{{ lookup('file', 'files/ssh-key') }}"

- name: dotfiles
  import_playbook: dotfiles.yml

- name: setup docent
  import_playbook: docent.yml

- name: setup iridium
  import_playbook: iridium.yml
