- hosts: all

  tasks:
    - name: Ensure .ssh directory exists.
      become: true
      file:
        dest: "/home/{{ lookup('env', 'USER') }}/.ssh"
        mode: 0700
        state: directory

    - name: Install ssh key
      copy:
        src: "files/id_ed25519"
        dest: "/home/{{ ansible_user_id }}/.ssh/id_ed25519"
        mode: 0644

    - name: Install ssh pub key
      copy:
        src: "files/id_ed25519.pub"
        dest: "/home/{{ ansible_user_id }}/.ssh/id_ed25519.pub"
        mode: 0644

    # - name: Set authorized key took from file
    #   authorized_key:
    #     user: "{{ lookup('env', 'USER') }}"
    #     state: present
    #     key: "/home/{{ ansible_user_id }}/.ssh/id_ed25519.pub"
