---
- name: Install apt packages
  become: true
  package:
    state: present
    name:
      - alacritty
      - bat
      - discord
      - exa
      - evolution
      - evolution-ews
      - gnome-tweaks
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-gsconnect-browsers
      - htop
      - neovim
      - python3-pip
      - snapd
      - stow
      - vim
      - virtualbox
      - code
      - zsh
      - git
      - tmux
      - tmuxinator
      - zsh-antigen

- name: install pexpect
  pip:
    name: pexpect
  become: true

- name: Install dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb

- name: Install flathub remote
  become: true
  community.general.flatpak_remote:
    state: present
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  become: true
  community.general.flatpak:
    state: present
    name:
      - com.jetbrains.IntelliJ-IDEA-Ultimate
      - com.spotify.Client
      - io.dbeaver.DBeaverCommunity
      - org.gnome.Evolution
      - org.keepassxc.KeePassXC

- name: Install snap packages
  become: true
  community.general.snap:
    state: present
    name:
      - snapd
      - authy
      - whatsdesk
